### ISSUE TITLE
指纹规则分类

### ISSUE THREAD

**Issue by grayguest** [webanalyzer/rules#1]
fate0师父好，请问是否应该考虑为指纹进行分类，比如wappalyzer里面有cats字段，可以粗粒度分类，比如前端技术、后端语言、后端框架、web容器、web应用 这五类。

**Comment by fate0** [comment]
因为 whatweb 和 fofa 的指纹规则都没有对应的分类，所以这块不是特别好做

**Comment by grayguest** [comment]
嗯，这块我的小想法是
把单一指纹规则的基础信息抽象为统一的，比如现在wappalyzer、whatweb、fofa、custom对于同一个指纹可能都有规则，那么把这些的基础信息统一，我目前是对规则的基础信息存在一个数据表里面。
先以某个指纹分类为准，比如wappalyzer，后续补充其他指纹分类，解决冲突。
最后感谢fate0师父的项目！
