### ISSUE TITLE
wappalyzer规则转换小BUG

### ISSUE THREAD

**Issue by grayguest** [webanalyzer/rules#4]
` 
r['confidence'] = int(value[len('confidence:'):])
`
wappalyzer现有有confidence为0.8的小数，可以把上面的代码改为
`
r['confidence'] = int(float(value[len('confidence:'):]))
`
即，加个float()转换即可

**Comment by fate0** [comment]
这个 https://github.com/AliasIO/Wappalyzer/pull/2766 已经 merge 了，按照 Wappalyzer 的编写规则来说，是不应该有小数存在的。
